### ISSUE TITLE
adopt usage of CSS Module Scripts

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/greenwood-lit-ssr#15]
Once [supported by the Lit team for SSR](https://github.com/lit/lit/issues/2631)  it would be nice to adopt CSS Module script in place of our inline usage of CSS
<details>
  <pre>
    -------------------------------------------------------
    Welcome to Greenwood (v0.30.0-alpha.2) ♻️
    -------------------------------------------------------
    Initializing project config
    Initializing project workspace contexts
    Generating graph of workspace files...
    building from local sources...
    (node:49224) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
    --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("./node_modules/%40greenwood/cli/src/loader.js", pathToFileURL("./"));'
    (Use `node --trace-warnings ...` to show where the warning was created)
    
    node:internal/process/promises:288
                triggerUncaughtException(err, true /* fromPromise */);
                ^
    ReferenceError [Error]: CSSStyleSheet is not defined
  </pre>
</details>

**Before**
```js
import { LitElement, html, css } from 'lit';

export class Card extends LitElement {
  static properties = {
    title: '',
    thumbnail: ''
  };
  static styles = css`
    div {
      display: flex;
      flex-direction: column;
      /* ... */
    }
  `;

  // ...
}

customElements.define('app-card', Card);
```

**After**
```css
/* card.css */
div {
  display: flex;
  flex-direction: column;
  /* ... */
}
```

```js
import { LitElement, html, css } from 'lit';
import sheet from './card.css' with { type: 'css' };

export class Card extends LitElement {
  static properties = {
    title: '',
    thumbnail: ''
  };
  static styles = [sheet];

  // ...
}

customElements.define('app-card', Card);
```

**Comment by thescientist13** [comment]
This may require a Node version bump depending on whatever Vercel's current supported version of NodeJS is
```sh
SyntaxError [Error]: Unexpected token 'with'
14:22:57.610 | at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:152:18)
14:22:57.610 | at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:298:14)
14:22:57.610 |  
14:22:57.610 | Node.js v18.19.1
14:22:57.634 | Error: Command "node --loader ./node_modules/@greenwood/cli/src/loader.js ./node_modules/.bin/greenwood build" exited with 1
14:22:57.851
```

**Comment by thescientist13** [comment]
This is now ready!
https://github.com/lit/lit/blob/main/packages/labs/ssr-dom-shim/CHANGELOG.md#150

**Comment by thescientist13** [comment]
Work being tracked here - https://github.com/ProjectEvergreen/greenwood/issues/1633

**Comment by thescientist13** [comment]
Made a test in #39 and ran into this issue when walking API routes
```
➜  greenwood-lit-ssr git:(chore/upgrade-greenwood-v0.34.0) ✗ pnpm run dev

> greenwood-demo-adapter-vercel@1.0.0 dev /Users/owenbuckley/Workspace/github/greenwood-lit-ssr
> NODE_OPTIONS='--import @greenwood/cli/register' greenwood develop

-------------------------------------------------------
Welcome to Greenwood (v0.34.0-alpha.6) ♻️
-------------------------------------------------------
Running Greenwood with the develop command.
Initializing project config
Initializing project workspace contexts
Generating graph of workspace files...
building from local sources...
ReferenceError: CSSStyleSheet is not defined
    at file:///Users/owenbuckley/Workspace/github/greenwood-lit-ssr/src/components/card/card.css:1:15
    at ModuleJob.run (node:internal/modules/esm/module_job:343:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:647:26)
    at async walkDirectoryForPages (file:///Users/owenbuckley/Workspace/github/greenwood-lit-ssr/node_modules/.pnpm/@greenwood+cli@0.34.0-alpha.6/node_modules/@greenwood/cli/src/lifecycles/graph.js:112:33)
    at async walkDirectoryForPages (file:///Users/owenbuckley/Workspace/github/greenwood-lit-ssr/node_modules/.pnpm/@greenwood+cli@0.34.0-alpha.6/node_modules/@greenwood/cli/src/lifecycles/graph.js:82:27)
    at async generateGraph (file:///Users/owenbuckley/Workspace/github/greenwood-lit-ssr/node_modules/.pnpm/@greenwood+cli@0.34.0-alpha.6/node_modules/@greenwood/cli/src/lifecycles/graph.js:326:9)
    at async generateCompilation (file:///Users/owenbuckley/Workspace/github/greenwood-lit-ssr/node_modules/.pnpm/@greenwood+cli@0.34.0-alpha.6/node_modules/@greenwood/cli/src/lifecycles/compile.js:113:19)
    at async run (file:///Users/owenbuckley/Workspace/github/greenwood-lit-ssr/node_modules/.pnpm/@greenwood+cli@0.34.0-alpha.6/node_modules/@greenwood/cli/src/index.js:12:25)
 ELIFECYCLE  Command failed with exit code 1.
```

Since API routes are effect-ful (see https://github.com/ProjectEvergreen/greenwood/issues/991)
