### ISSUE TITLE
restore products page (support `async` work in Lit SSR page routes)

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/greenwood-lit-ssr#3]
Unfortunately the products page is not working currently because of a couple issues
1. [ ] There is no way in Lit (SSR) to do any [`async` work](https://lit.dev/docs/ssr/overview/#library-status) it seems, and so the content is empty - https://github.com/thescientist13/greenwood-demo-adapter-vercel-lit/issues/3#issuecomment-1766740839
    ![Screenshot 2023-10-12 at 8 44 53 AM](https://github.com/thescientist13/greenwood-demo-adapter-vercel-lit/assets/895923/ec63386b-e25d-4d54-8516-c9131da51fc6)
1. [ ] Production bundling / serving seems to broken - https://github.com/thescientist13/greenwood-demo-adapter-vercel-lit/issues/3#issuecomment-1766757224
1. [ ] Seems when testing with `sync` work, the content is duplicated?  Might need a lit polyfill for this?
  ![Screenshot 2023-11-20 at 4 41 42 PM](https://github.com/thescientist13/greenwood-demo-adapter-vercel-lit/assets/895923/5f51bbe1-0f23-40b1-a877-e47db0262d3e)

> _If we can solve these, we should update the [**Caveats** section](https://github.com/ProjectEvergreen/greenwood/tree/v0.29.0-alpha.6/packages/plugin-renderer-lit#caveats) of the Lit renderer plugin docs_

**Comment by thescientist13** [comment]
Regarding async work..

The hope is that something like this in our SSR page routes.
```js
import { html, LitElement } from 'lit';
import { getProducts } from '../services/products.js';
import '../components/card.js';

export default class ProductsPage extends LitElement {

  constructor() {
    super();
    this.products = [];
  }

  async connectedCallback() {
    super.connectedCallback();

    this.products = await getProducts();
  }

  render() {
    // ...
  }
}

// for now these are needed for the Lit specific implementations
customElements.define('products-page', ProductsPage);
export const tagName = 'products-page';
```

We should contribute to some of the following conversations
- https://github.com/lit/lit/issues/3219
- https://github.com/lit/lit/issues/2469

**Comment by thescientist13** [comment]
Regarding bundling / serving, I think these errors are both probably related to - https://github.com/ProjectEvergreen/greenwood/issues/1118

When building we can see our =["hack" around dynamically generating output files](https://github.com/ProjectEvergreen/greenwood/blob/v0.29.0-alpha.5/packages/cli/src/config/rollup.config.js#L277) is not picking up on our _products.js_ page route
```sh
$ greenwood build
-------------------------------------------------------
Welcome to Greenwood (v0.29.0-alpha.5) ♻️
-------------------------------------------------------
Initializing project config
Initializing project workspace contexts
Generating graph of workspace files...
building from local sources...
Running Greenwood with the build command.
pages to generate
 /
 /search/
 /404/
generated page... /
generated page... /404/
generated page... /search/
success, done generating all pages!
bundling static assets...
Circular dependency: node_modules/@lit-labs/ssr/lib/render-lit-html.js -> node_modules/@lit-labs/ssr/lib/lit-element-renderer.js -> node_modules/@lit-labs/ssr/lib/render-lit-html.js
Could not find entry path match for bundle => __products.js
optimizing static pages....
copying file... src/favicon.ico
copying file... .greenwood/manifest.json
✨  Done in 1.57s.
```

Then when actually serving the page, we get `window is not defined` error
```sh
-------------------------------------------------------
Welcome to Greenwood (v0.29.0-alpha.5) ♻️
-------------------------------------------------------
Initializing project config
Initializing project workspace contexts
Loading graph from build output...
Loading manifest from build output...
Loading resources from build output...
Running Greenwood with the serve command.
Started server at localhost:8080
ReferenceError: window is not defined
    at file:///Users/owenbuckley/Workspace/github/greenwood-demo-adapter-vercel-lit/public/lit-element.8119ea05.js:6:11
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async file:///Users/owenbuckley/Workspace/github/greenwood-demo-adapter-vercel-lit/node_modules/@greenwood/cli/src/lifecycles/serve.js:297:29
    at async file:///Users/owenbuckley/Workspace/github/greenwood-demo-adapter-vercel-lit/node_modules/@greenwood/cli/src/lifecycles/serve.js:275:7
    at async file:///Users/owenbuckley/Workspace/github/greenwood-demo-adapter-vercel-lit/node_modules/@greenwood/cli/src/lifecycles/serve.js:233:5
    at async file:///Users/owenbuckley/Workspace/github/greenwood-demo-adapter-vercel-lit/node_modules/@greenwood/cli/src/lifecycles/serve.js:200:5
```
![Screenshot 2023-10-13 at 9 37 51 PM](https://github.com/thescientist13/greenwood-demo-adapter-vercel-lit/assets/895923/66397026-b2a6-4e1d-9546-a5f0249d4738)

----

The reason I think this is bundling related is if I look at the _public/__products.js_ file, we can see it is not inlining the `handler` function
```js
export { h as handler } from './_products.86331d20.js';
import 'node:http';
import 'node:https';
import 'node:zlib';
import 'node:stream';
import 'node:buffer';
import 'node:util';
import 'node:url';
import 'node:net';
import 'node:fs';
import 'node:path';
import './lit-element.8119ea05.js';
import 'buffer';
import 'stream';
```

For example, our test case, the bundled SSR page would look like this
```js
import { e as executeRouteModule } from './execute-route-module.6d1fac51.js';
import 'stream';
import 'http';
import 'url';
import 'punycode';
import 'https';
import 'zlib';
import 'module';
import 'buffer';

async function handler(request) {
  // ...
  const moduleUrl = new URL('./_artists.js', import.meta.url);
}

export { handler };
```

---

My hope is that by implementing https://github.com/ProjectEvergreen/greenwood/issues/1118 we can eliminate any chunking in our SSR and API routes so that we can get one single, predictable, file output.

**Comment by thescientist13** [comment]
Some additional reading / research
- https://github.com/lit/lit/releases/tag/%40lit-labs%2Fssr%403.2.0 (server only `html` function)
- https://github.com/lit/lit/pull/4390
